apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-quarkus
  namespace: todos
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: todos-api-quarkus
  template:
    metadata:
      labels:
        app: todos-api-quarkus
    spec:
      imagePullSecrets:
        - name: regcred-github
      containers:
        - name: todos-api-quarkus
          image: docker.pkg.github.com/guillaumedeconinck/todos-backend-quarkus/todos-api-quarkus:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
